1. 특정한 경로에 있는 파일의 목록을 로드
2. 목록들을 모두 데이터프레임 로드(read_함수 사용)
3. 단순한 행 결합을 이용하여 하나의 데이터프레임 생성

In [1]:
# 라이브러리 로드
import pandas as pd
import os

In [2]:
# 특정한 경로의 파일의 목록
# listdir({경로})
# os라이브러리 안에 있는 함수
file_list = os.listdir("./csv/2017/")

In [3]:
file_path = "./csv/2017/"
file_list = os.listdir(file_path)

# 빈 데이터프레임 생성
df_2017 = pd.DataFrame()

for i in file_list:
    df = pd.read_csv(file_path+i)
    df_2017 = pd.concat([df_2017,df], axis=0)

In [4]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70132 entries, 0 to 7285
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                70132 non-null  int64
 1   title              70132 non-null  object
 2   url                70132 non-null  object
 3   dept_nm_lvl_1      70132 non-null  object
 4   dept_nm_lvl_2      70074 non-null  object
 5   dept_nm_lvl_3      61262 non-null  object
 6   dept_nm_lvl_4      17939 non-null  object
 7   dept_nm_lvl_5      3474 non-null   object
 8   exec_yr            70132 non-null  int64
 9   exec_month         70132 non-null  int64
 10  expense_budget     3108 non-null   float64
 11  expense_execution  2805 non-null   float64
 12  category           1259 non-null   object
 13  dept_nm_full       70053 non-null  object
 14  exec_dt            70132 non-null  object
 15  exec_loc           69360 non-null  object
 16  exec_purpose       70110 non-null  object
 17  target_nm          69597 non-null  object
 18  payment_method     69929 non-null  object
 19  exec_amount        70132 non-null  int64
dtypes: float64(2), int64(4), object(14)
memory usage: 11.2+ MB

In [5]:
# json 파일 불러와서 결합
file_path = "./csv/2019/"
file_list = os.listdir(file_path)

df_2019 = pd.DataFrame()

for i in file_list:
    df = pd.read_json(file_path+i)
    df_2019 = pd.concat([df_2019,df], axis=0)
    
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74207 entries, 0 to 7843
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                74207 non-null  int64
 1   title              74207 non-null  object
 2   url                74207 non-null  object
 3   dept_nm_lvl_1      74207 non-null  object
 4   dept_nm_lvl_2      74207 non-null  object
 5   dept_nm_lvl_3      74207 non-null  object
 6   dept_nm_lvl_4      74207 non-null  object
 7   dept_nm_lvl_5      74207 non-null  object
 8   exec_yr            74207 non-null  int64
 9   exec_month         74207 non-null  int64
 10  expense_budget     2075 non-null   float64
 11  expense_execution  1598 non-null   float64
 12  category           74028 non-null  object
 13  dept_nm_full       74207 non-null  object
 14  exec_dt            74207 non-null  object
 15  exec_loc           74207 non-null  object
 16  exec_purpose       74207 non-null  object
 17  target_nm          74207 non-null  object
 18  payment_method     74207 non-null  object
 19  exec_amount        74207 non-null  int64
dtypes: float64(2), int64(4), object(14)
memory usage: 11.9+ MB

In [6]:
# Excel 파일 불러와서 결합
file_path = "./csv/2020/"
file_list = os.listdir(file_path)

df_2020 = pd.DataFrame()

for i in file_list:
    df = pd.read_excel(file_path+i)
    df_2020 = pd.concat([df_2020,df], axis=0)
    
df_2020.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70862 entries, 0 to 7814
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                70862 non-null  int64
 1   title              70862 non-null  object
 2   url                70862 non-null  object
 3   dept_nm_lvl_1      70862 non-null  object
 4   dept_nm_lvl_2      70862 non-null  object
 5   dept_nm_lvl_3      55593 non-null  object
 6   dept_nm_lvl_4      18992 non-null  object
 7   dept_nm_lvl_5      1601 non-null   object
 8   exec_yr            70862 non-null  int64
 9   exec_month         70862 non-null  int64
 10  expense_budget     1823 non-null   float64
 11  expense_execution  1338 non-null   float64
 12  category           2123 non-null   object
 13  dept_nm_full       70862 non-null  object
 14  exec_dt            70862 non-null  object
 15  exec_loc           70278 non-null  object
 16  exec_purpose       70862 non-null  object
 17  target_nm          70488 non-null  object
 18  payment_method     70862 non-null  object
 19  exec_amount        70862 non-null  int64
 20  bimok              283 non-null    object
dtypes: float64(2), int64(4), object(15)
memory usage: 11.9+ MB

In [7]:
# 파일을 불러와서 결합하는 과정을 함수로 만들어 놓고, 필요시마다 함수를 호출하여 사용 

def list_data(_path, _end):
    # _path는 파일의 경로
    # 경로의 파일 목록 로드
    file_list = os.listdir(_path)
    
    # 특정한 확장자의 파일 목록을 만들기 위해 비어있는 리스트를 생성
    file_list2 = []
   
    for i in file_list:
        if i.split('.')[-1] == _end:
            file_list2.append(i) 
    
    # 함수의 결과값 -> 비어있는 데이터프레임
    result = pd.DataFrame()
    
    # 반복문을 이용하여 파일 목록들을 데이터프레임 로드하고 result 에 행결합
    for i in file_list2:
        # 로드하고자 하는 파일의 확장자가 다른경우 해당 조건에 맞게 실행되도록 if조건문 작성
        # _end 가 csv 라면 read_csv()
        # _end 가 json 라면 read_json()
        # _end 가 xlsx,xls 라면 read_excel()
        if _end =='csv':
            df =  pd.read_csv(_path+'/'+i)
        elif _end =='json':
            df =  pd.read_json(_path+'/'+i)
        elif _end in ['xlsx','xls']:
            df =  pd.read_excel(_path+'/'+i)
        else:
            return "지원하지 않는 확장자입니다."       
        # df = pd.read_csv(_path+'/'+i) # 혹시 경로에 마지막 '/'를 추가하지 않는 경우에도 오류가 발생하지 않도록 '/' 추가 ('/'가 2개여도 정상작동)
        result = pd.concat([result,df], axis=0)

    return result

In [8]:
list_data("./csv/2021/", "csv")

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,...,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount,bimok
0,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 관리과,2021-01-25 00:00,NaN,소속직원 경조사비,"김광옥, 김용성",현금,100000,NaN
1,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 운영과,2021-01-22 00:00,복시루,운영과 다과구매-전출직원선물,NaN,카드,90000,NaN
2,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 시설보수과,2021-01-21 00:00,떡시루,소속직원 송별떡,시설보수과장외 27명,카드,80000,NaN
3,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 운영과,2021-01-21 00:00,서울시청매점,운영과 다과구매-전출직원선물,NaN,제로페이,48000,NaN
4,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 운영과,2021-01-21 00:00,복시루,운영과 다과구매-전출직원선물,NaN,카드,75000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10339,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-21 19:44,고기사람(서대문구 충정로4길 26),사업소간 교차점검 결과보고 간담회,소장 외 2명,카드,97000,NaN
10340,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-07 11:57,장수숯불갈비(성동구 성덕정길40),신임소장과 전직원 순회 소통 (D팀) 간담회,소장 외 5명,카드,120000,NaN
10341,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-02 12:07,장수숯불갈비(성동구 성덕정길39),신임소장과 전직원 순회 소통 (C팀) 간담회,소장 외 7명,카드,116000,NaN
10342,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-28 16:48,현대마트(성동구 성덕정길29),기관운영 물품 구매,소장,카드,113180,NaN
10343,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-28 10:15,서울시청매점(중구 덕수궁길),소장실 운영물품 구매,소장,카드,84000,NaN

In [9]:
file_list[0].split('.')[-1]

'xlsx'

In [10]:
for i in file_list:
    # '.'을 기준으로 맨 뒤 내용 : 확장자가 csv인 경우
    if i.split('.')[-1] == 'csv':
        print(i)
        
        
for i in file_list:
    # 문자열의 마지막 값과 비교
    if i.endswith('csv'):
        print(i)